export type UpgradeKind = string;
export type UpgradeRarity = 'Common' | 'Uncommon' | 'Rare' | 'Epic' | 'Legendary';

export interface UpgradeDefinition {
  id: UpgradeKind;
  title: string;
  description: string;
  rarity: UpgradeRarity;
  target: 'ballista' | 'cannon' | 'fire' | 'lightning' | 'mortar' | 'general';
}

export const RARITY_WEIGHTS: Record<UpgradeRarity, number> = { Common: 55, Uncommon: 25, Rare: 12, Epic: 6, Legendary: 2 };
export const EVOLUTION_IDS = new Set(['boltStorm', 'carpetBombardment', 'hellfire', 'thunderstorm']);
export const EVOLUTION_DEFINITIONS: Record<string, UpgradeDefinition> = {
  boltStorm: { id: 'boltStorm', title: 'BOLT STORM', description: 'A devastating piercing Ballista barrage.', rarity: 'Legendary', target: 'ballista' },
  carpetBombardment: { id: 'carpetBombardment', title: 'CARPET BOMBARDMENT', description: 'Cannon impacts saturate the battlefield.', rarity: 'Legendary', target: 'cannon' },
  hellfire: { id: 'hellfire', title: 'HELLFIRE', description: 'Wildfire becomes an inferno.', rarity: 'Legendary', target: 'fire' },
  thunderstorm: { id: 'thunderstorm', title: 'THUNDERSTORM', description: 'Lightning storms across the horde.', rarity: 'Legendary', target: 'lightning' },
};

export const UPGRADE_DEFINITIONS: readonly UpgradeDefinition[] = [
  { id: 'damage', title: 'Hardened Bolts', description: 'Ballista damage increases by 25 percent.', rarity: 'Common', target: 'ballista' }, { id: 'attackSpeed', title: 'Winch Crew', description: 'Ballista fixed line fire rate increases by 20 percent.', rarity: 'Common', target: 'ballista' }, { id: 'range', title: 'Long Sightline', description: 'Ballista firing corridor length increases by 20 percent.', rarity: 'Common', target: 'ballista' }, { id: 'projectileSpeed', title: 'Steel Flight', description: 'Projectile speed increases by 35 percent.', rarity: 'Uncommon', target: 'ballista' }, { id: 'criticalChance', title: 'Deadeye Order', description: 'Critical chance increases by 12 percent.', rarity: 'Uncommon', target: 'ballista' }, { id: 'criticalDamage', title: 'Execution Bolts', description: 'Critical damage increases by 50 percent.', rarity: 'Rare', target: 'ballista' }, { id: 'penetration', title: 'Piercing Bolts', description: 'Bolts pass through one more enemy.', rarity: 'Uncommon', target: 'ballista' }, { id: 'projectiles', title: 'Volley Doctrine', description: 'Ballista fires one additional parallel bolt.', rarity: 'Rare', target: 'ballista' },
  { id: 'cannonDamage', title: 'Heavy Shells', description: 'Cannon shell damage increases.', rarity: 'Common', target: 'cannon' }, { id: 'cannonRadius', title: 'Wide Blast', description: 'Cannon impact radius increases.', rarity: 'Uncommon', target: 'cannon' }, { id: 'cannonRange', title: 'Measured Impact', description: 'Cannon aim distance and detonation reach increase.', rarity: 'Common', target: 'cannon' }, { id: 'cannonSpeed', title: 'Rapid Loading', description: 'Cannon fires faster.', rarity: 'Common', target: 'cannon' }, { id: 'clusterShells', title: 'Cluster Shells', description: 'Cannon adds a secondary fixed distance blast.', rarity: 'Rare', target: 'cannon' }, { id: 'doubleBarrel', title: 'Double Barrel', description: 'Cannon fires an additional shell along its locked line.', rarity: 'Epic', target: 'cannon' },
  { id: 'fireDamage', title: 'Hotter Flames', description: 'Fire cone burn damage increases.', rarity: 'Common', target: 'fire' }, { id: 'fireDuration', title: 'Slow Burn', description: 'Fire cone burn lasts longer.', rarity: 'Common', target: 'fire' }, { id: 'fireRadius', title: 'Longer Cone', description: 'Fire cone reaches farther.', rarity: 'Uncommon', target: 'fire' }, { id: 'fireCone', title: 'Wider Cone', description: 'Fire cone angle increases.', rarity: 'Uncommon', target: 'fire' }, { id: 'fireSpread', title: 'Wildfire', description: 'Fire spreads on death.', rarity: 'Rare', target: 'fire' }, { id: 'hellfire', title: 'Hellfire', description: 'Burning enemies erupt inside the fixed cone.', rarity: 'Legendary', target: 'fire' },
  { id: 'lightningDamage', title: 'Charged Coils', description: 'Lightning damage increases.', rarity: 'Common', target: 'lightning' }, { id: 'lightningChains', title: 'Forked Arc', description: 'Lightning chains to more foes.', rarity: 'Uncommon', target: 'lightning' }, { id: 'lightningRange', title: 'Zone Reach', description: 'Lightning target zone and chain range increase.', rarity: 'Common', target: 'lightning' }, { id: 'lightningStun', title: 'Static Lock', description: 'Lightning stuns targets.', rarity: 'Rare', target: 'lightning' }, { id: 'thunderstorm', title: 'Thunderstorm', description: 'Lightning chains become more powerful inside the locked zone.', rarity: 'Legendary', target: 'lightning' },
  { id: 'mortarDamage', title: 'Heavy Mortar', description: 'Mortar shell damage increases.', rarity: 'Common', target: 'mortar' }, { id: 'mortarSpeed', title: 'Rapid Reload', description: 'Mortar bombardment rate increases.', rarity: 'Common', target: 'mortar' }, { id: 'mortarRadius', title: 'Blast Pattern', description: 'Mortar target area and blast radius increase.', rarity: 'Uncommon', target: 'mortar' }, { id: 'mortarRange', title: 'High Arc', description: 'Mortar target distance increases.', rarity: 'Uncommon', target: 'mortar' }, { id: 'doubleShot', title: 'Double Shot', description: 'Mortar fires more frequently into its locked area.', rarity: 'Rare', target: 'mortar' },
  { id: 'repair', title: 'Field Repair', description: 'Repair the wall by 20 HP.', rarity: 'Common', target: 'general' }, { id: 'wallMax', title: 'Emergency Masonry', description: 'Wall maximum HP increases.', rarity: 'Uncommon', target: 'general' }, { id: 'goldBonus', title: 'Bounty Surge', description: 'Gold rewards increase.', rarity: 'Uncommon', target: 'general' }, { id: 'abilityHaste', title: 'Sky Command', description: 'Ability cooldowns shorten.', rarity: 'Rare', target: 'general' }, { id: 'boltStorm', title: 'Bolt Storm', description: 'Ballista fires a devastating volley.', rarity: 'Legendary', target: 'ballista' },
] as const;
